name: Automatische Bewertung des Jupyter Notebooks in neuer Umgebung

on:
  push:
    branches:
      - main 

jobs:
<<<<<<< HEAD
  check_cell:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: Lösche die result.txt, wenn sie existiert
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          if [ -f Aufgaben/01/result.txt ]; then
            git rm Aufgaben/01/result.txt
            git commit -m "Löschen der Datei result.txt"
          else
            echo "result.txt existiert nicht und wurde daher nicht gelöscht"
          fi

      - name: Installiere Abhängigkeiten
        run: pip install nbformat

      - name: Suche nach Markierung im Jupyter Notebook
        run: python check_notebook_marker_new.py

      - name: Pushe die result.txt ins Repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add Aufgaben/01/result.txt
          git commit -m "Überprüfung, ob gesuchte Zelle vorhanden ist, erfolgreich." --allow-empty --no-verify
          git pull --rebase origin main || (git rebase --abort && echo "Rebase fehlgeschlagen, führe Merge durch")
          git pull --no-rebase
          git push
          
      - name: Speichere result.txt als Artifact
        uses: actions/upload-artifact@v4
        with:
          name: result-file
          path: Aufgaben/01/result.txt

=======
>>>>>>> 6ef5c29af9013f6cba130699a47de1dcff5d6935
  bewerten_notebook:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: Installiere Abhängigkeiten
        run: pip install nbformat

      - name: Führe Code aus und bewerte das Ergebnis
        run: python grading.py

<<<<<<< HEAD
      - name: Pushe die Bewertung.txt ins Repository
=======
      - name: Pushe das aktualisierte Jupyter Notebook ins Repository
>>>>>>> 6ef5c29af9013f6cba130699a47de1dcff5d6935
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add Testbook.ipynb
          git commit -m "Automatische Bewertung ins Notebook eingefügt" --allow-empty
          git pull --rebase origin main || (git rebase --abort && echo "Rebase fehlgeschlagen, führe Merge durch")
          git pull --no-rebase
          git push
