name: Check Jupyter Notebook for Task

on:
  push:
    branches:
      - main 

jobs:
  check_notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: Installiere Abhängigkeiten
        run: pip install nbformat

      - name: Überprüfe das Jupyter Notebook
        run: python check_notebook.py

      - name: Konfiguriere Git und pushe die result.txt ins Repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add result.txt
          git commit -m "Automatische Überprüfung des Jupyter Notebooks durchgeführt" --allow-empty
          git push
